config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  resources :admins
  resources :instructors
  resources :waitlists
  resources :students
  resources :courses
  resources :enrollments
  resources :sessions, only: [:new, :create, :destroy]
  get 'admin_signup', to: "admins#new", as: 'admin_signup'
  get 'student_signup', to: "students#new", as: 'student_signup'
  get 'instructor_signup', to: "instructors#new", as: 'instructor_signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get 'instructor_courses', to: "courses#show_instructor_courses", as: "instructor_courses"
  get 'student_enrollments', to: "courses#show_student_enrolled_courses", as: "student_enrollments"
  get 'show_instructor_students_enrolled', to: "enrollments#show_instructor_students_enrolled", as: "show_instructor_students_enrolled"
  get 'show_instructor_students_waitlisted', to: "waitlists#show_instructor_students_waitlisted", as: "show_instructor_students_waitlisted"
  get 'student_waitlists', to: "courses#show_student_waitlisted_courses", as: "student_waitlists"
  get 'all_enrollments', to: "admins#all_enrollments", as: "all_enrollments"
  get 'show_instructor_students' , to: "instructors#show_instructor_students", as: "show_instructor_students"
  resources :courses do
    member do
      get 'enroll'
    end
  end
  resources :enrollments do
    member do
      get 'unenroll'
    end
  end
  resources :courses do
    member do
      get 'drop'
    end
  end

  resources :courses do
    member do
      get 'drop_waitlist'
    end
  end

  resources :courses do
    member do
      get 'all_students'
    end
  end

  resources :waitlists do
    member do
      get 'remove_list'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/waitlists_controller.rb
class WaitlistsController < ApplicationController
  before_action :correct_code, only: [:edit, :update, :destroy, :show]
  before_action :set_waitlist, only: %i[ show edit update destroy ]

  # GET /waitlists or /waitlists.json
  def index
    unless check_permissions?(session[:user_role], "view_waitlist")
      redirect_to root_path
    end
    @waitlists = Waitlist.all
  end

  # GET /waitlists/1 or /waitlists/1.json
  def show
    unless check_permissions?(session[:user_role], "show_waitlist")
      redirect_to root_path
    end
  end

  # GET /waitlists/new
  def new
    unless check_permissions?(session[:user_role], "create_waitlist")
      redirect_to root_path
    end
    @waitlist = Waitlist.new
  end

  # GET /waitlists/1/edit
  def edit
    unless check_permissions?(session[:user_role], "edit_waitlist")
      redirect_to root_path
    end
  end

  def correct_code
    if Waitlist.find_by_id(params[:id]).nil?
      redirect_to root_path
    end
  end

  def show_instructor_students_waitlisted
    unless check_permissions?(session[:user_role], "show_instructor_students_waitlisted")
      redirect_to root_path
    end
    @waitlists = Waitlist.where(instructor_id: Instructor.find_by_user_id(session[:user_id]).id)
  end

  # POST /waitlists or /waitlists.json
  def create
    unless check_permissions?(session[:user_role], "create_waitlist")
      redirect_to root_path
    end

    @waitlist = Waitlist.new(waitlist_params)
    @course = Course.find_by_course_code(@waitlist.course_code)
    @student = Student.find_by_student_id(@waitlist.student_code)

    if @student.nil?
      flash[:alert] = "Student doesn't exist"
      redirect_to new_waitlist_path
      return
    elsif @course.nil?
      flash[:alert] = "Course doesn't exist"
      redirect_to new_waitlist_path
      return
    end

    @instructor = Instructor.find_by_id(@course.instructor_id)
    @waitlist.student_id = @student.id
    @waitlist.course_id = @course.id
    @waitlist.instructor_id = @instructor.id

    already_enrolled = !Enrollment.where(student_id: @student.id, course_id: @course.id)[0].nil?
    already_waitlisted = !Waitlist.where(student_id: @student.id, course_id: @course.id)[0].nil?

    if current_user.user_role == 'instructor'
      respond_to do |format|
        if current_user.user_role == 'instructor' and session[:user_id] == @instructor.user_id
          if already_enrolled
            format.html { redirect_to show_instructor_students_waitlisted_path, alert: @student.name.to_s + " is already enrolled in " + @course.course_code.to_s }
            format.json { render json: @enrollment.errors, status: :unprocessable_entity }
          else
            if @course.status != 'CLOSED'
              if already_waitlisted
                format.html { redirect_to show_instructor_students_waitlisted_path, alert: @student.name.to_s + " is already waitlisted in " + @course.course_code.to_s }
                format.json { render json: @waitlist.errors, status: :unprocessable_entity }
                #render show_instructor_students_waitlisted_path
              else
                if @course.students_waitlisted < @course.waitlist_capacity
                  if @waitlist.save
                    @course.update(students_waitlisted: (@course.students_waitlisted + 1))
                    format.html { redirect_to show_instructor_students_waitlisted_path, alert: @student.name.to_s + " is successfully waitlisted in " + @course.course_code.to_s }
                    format.json { render :show, status: :created, location: @waitlist }
                    if @course.students_enrolled == @course.capacity
                      if @course.waitlist_capacity == @course.students_waitlisted
                        @course.update(status: "CLOSED")
                      end
                    end
                  else
                    format.html { render :new, status: :unprocessable_entity }
                    format.json { render json: @waitlist.errors, status: :unprocessable_entity }
                  end
                else
                  format.html { redirect_to show_instructor_students_waitlisted_path, alert: "Waitlist capacity is full" }
                  format.json { render json: @waitlist.errors, status: :unprocessable_entity }
                end
              end
            else
              format.html { redirect_to show_instructor_students_waitlisted_path, alert: @student.name.to_s + " can't be waitlisted in " + @course.course_code.to_s + " since, the course is CLOSED" }
              format.json { render json: @waitlist.errors, status: :unprocessable_entity }
            end
          end
        else
          format.html { redirect_to show_instructor_students_waitlisted_path, alert: "You cannot waitlist student in courses other than yours" }
          format.json { render json: @waitlist.errors, status: :unprocessable_entity }
        end
      end
    elsif current_user.user_role == "admin"
      respond_to do |format|
        if already_enrolled
          format.html { redirect_to admins_path, alert: @student.name.to_s + " is already enrolled in " + @course.course_code.to_s }
          format.json { render json: @enrollment.errors, status: :unprocessable_entity }
        else
          if @course.status == 'WAITLIST'
            if already_waitlisted
              format.html { redirect_to admins_path, alert: @student.name.to_s + " is already waitlisted in " + @course.course_code.to_s }
              format.json { render json: @waitlist.errors, status: :unprocessable_entity }
            else
              if @course.students_waitlisted < @course.waitlist_capacity
                if @waitlist.save
                  format.html { redirect_to admins_path, notice: @student.name.to_s + " is successfully waitlisted in " + @course.course_code.to_s }
                  format.json { render :show, status: :created, location: @waitlist }
                  @course.update(students_waitlisted: (@course.students_waitlisted + 1))
                  if @course.waitlist_capacity == @course.students_waitlisted
                    @course.update(status: "CLOSED")
                  end
                else
                  format.html { render :new, status: :unprocessable_entity }
                  format.json { render json: @waitlist.errors, status: :unprocessable_entity }
                end
              else
                format.html { redirect_to admins, alert: "Waitlist capacity is full" }
                format.json { render json: @waitlist.errors, status: :unprocessable_entity }
              end
            end
          elsif @course.status == 'CLOSED'
            format.html { redirect_to admins_path, alert: @student.name.to_s + " can't be waitlisted in " + @course.course_code.to_s + " since, the course is CLOSED" }
            format.json { render json: @waitlist.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # PATCH/PUT /waitlists/1 or /waitlists/1.json
  def update
    respond_to do |format|
      if @waitlist.update(waitlist_params)
        format.html { redirect_to waitlist_url(@waitlist), notice: "Waitlist was successfully updated." }
        format.json { render :show, status: :ok, location: @waitlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_list
    unless check_permissions?(session[:user_role], "remove_waitlist")
      redirect_to root_path
    end

    @waitlist = Waitlist.find_by_id(params[:id])

    @course = Course.find_by_id(@waitlist.course_id)
    @student = Student.find_by_id(@waitlist.student_id)

    @course.update(students_waitlisted: (@course.students_waitlisted - 1))
    if @course.status = "CLOSED"
      @course.update(status: "WAITLIST")
    end

    @waitlist.destroy

    respond_to do |format|
      format.html { redirect_to show_instructor_students_path, notice: @student.name.to_s + " has been successfully removed from waitlist in " + @course.course_code.to_s }
      format.json { head :no_content }
    end
  end

  # DELETE /waitlists/1 or /waitlists/1.json
  def destroy
    unless check_permissions?(session[:user_role], "delete_waitlist")
      redirect_to root_path
    end

    @course = Course.find_by_id(@waitlist.course_id)

    @course.update(students_waitlisted: (@course.students_waitlisted - 1))
    if @course.status = "CLOSED"
      @course.update(status: "WAITLIST")
    end

    @waitlist.destroy

    respond_to do |format|
      format.html { redirect_to waitlists_url, notice: "Waitlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_waitlist
    @waitlist = Waitlist.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def waitlist_params
    params.require(:waitlist).permit(:student_code, :course_code)
  end
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/waitlists/_form.html.erb
<%= form_with(model: waitlist) do |form| %>
  <% if waitlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(waitlist.errors.count, "error") %> prohibited this waitlist from being saved:</h2>

      <ul>
        <% waitlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :"Student ID", style: "display: block" %>
    <%= form.select :student_code, Student.all.order("student_id ASC").collect { |x| [x.student_id] } %>
    <%#= form.text_field :student_code %>
  </div>

  <div>
    <%= form.label :"Course Code", style: "display: block" %>
    <%= form.select :course_code, Course.all.order("course_code ASC").collect { |x| [x.course_code] } %>
    <%#= form.text_field :course_code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/waitlists/_waitlist.html.erb
<div id="<%= dom_id waitlist %>">
  <p>
    <strong>Student:</strong>
    <%= waitlist.student_code %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= waitlist.course_code %>
  </p>

</div>

app/views/waitlists/edit.html.erb
<h1>Editing waitlist</h1>

<%= render "form", waitlist: @waitlist %>

<br>

<div>
  <%= link_to "Show this waitlist", @waitlist %> |
  <%= link_to "Back to waitlists", waitlists_path %>
</div>

app/views/waitlists/index.html.erb
<h1>Waitlists</h1>

<table>
  <thead>
  <tr>
    <th> Student ID</th>
    <th> Course Code</th>
    <th colspan="1"></th>
  </tr>
  </thead>
  <tbody>
  <% @waitlists.each do |waitlist| %>
    <tr>
      <td><%= waitlist.student_code %></td>
      <td><%= waitlist.course_code %></td>
      <td><%= link_to "Show this waitlist", waitlist %></td>
  <% end %>
  </tr>
  </tbody>
</table>

<br>
<%= link_to "New Enrollment", new_enrollment_path %>
<%#= link_to "New waitlist", new_waitlist_path %>

app/views/waitlists/new.html.erb
<h1>New waitlist</h1>
<b><p style="color: red"><%= alert %></p></b>


<%= render "form", waitlist: @waitlist %>

<br>

<div>
  <%= link_to "Back to waitlists", waitlists_path %>
</div>

app/views/waitlists/show.html.erb
<%= render @waitlist %>

<div>
  <!--  <%#= link_to "Edit this waitlist", edit_waitlist_path(@waitlist) %> <br><br>-->
  <%= button_to "Destroy this waitlist", @waitlist, method: :delete %><br>

  <% if current_user.user_role == 'admin' %>
    <%= link_to "All Enrollments", all_enrollments_path %> <br><br>
  <% elsif current_user.user_role == 'instructor' %>
    <%= link_to "My Students", show_instructor_students_path %><br><br>
  <% end %>

  <%= link_to "Back to waitlists", waitlists_path %>
</div>

app/views/waitlists/show_instructor_students_waitlisted.html.erb
<h1>My Course Waitlisted Students</h1>

<table>
  <thead>
  <tr>
    <th>Course Code</th>
    <th>Student Code</th>
    <th>Student Name</th>
    <th>Email</th>
    <th>Date of Birth</th>
    <th>Phone Number</th>
    <th>Major</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @waitlists.each do |waitlist| %>
    <tr>
      <td><%= waitlist.course_code %></td>
      <td><%= waitlist.student_code %></td>
      <td><%= Student.find_by_id(waitlist.student_id).name %></td>
      <td><%= Student.find_by_id(waitlist.student_id).email %></td>
      <td><%= Student.find_by_id(waitlist.student_id).date_of_birth %></td>
      <td><%= Student.find_by_id(waitlist.student_id).phone_number %></td>
      <td><%= Student.find_by_id(waitlist.student_id).major %></td>
      <td><%= link_to 'Remove', remove_list_waitlist_path(waitlist), method: :post, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>



<% if current_user.user_role != 'student' %>
<%= link_to "New Waitlist", new_waitlist_path %>
<% end %>
<%#= link_to 'Back', root_path %>