config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  resources :admins
  resources :instructors
  resources :waitlists
  resources :students
  resources :courses
  resources :enrollments
  resources :sessions, only: [:new, :create, :destroy]
  get 'admin_signup', to: "admins#new", as: 'admin_signup'
  get 'student_signup', to: "students#new", as: 'student_signup'
  get 'instructor_signup', to: "instructors#new", as: 'instructor_signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get 'instructor_courses', to: "courses#show_instructor_courses", as: "instructor_courses"
  get 'student_enrollments', to: "courses#show_student_enrolled_courses", as: "student_enrollments"
  get 'show_instructor_students_enrolled', to: "enrollments#show_instructor_students_enrolled", as: "show_instructor_students_enrolled"
  get 'show_instructor_students_waitlisted', to: "waitlists#show_instructor_students_waitlisted", as: "show_instructor_students_waitlisted"
  get 'student_waitlists', to: "courses#show_student_waitlisted_courses", as: "student_waitlists"
  get 'all_enrollments', to: "admins#all_enrollments", as: "all_enrollments"
  get 'show_instructor_students' , to: "instructors#show_instructor_students", as: "show_instructor_students"
  resources :courses do
    member do
      get 'enroll'
    end
  end
  resources :enrollments do
    member do
      get 'unenroll'
    end
  end
  resources :courses do
    member do
      get 'drop'
    end
  end

  resources :courses do
    member do
      get 'drop_waitlist'
    end
  end

  resources :courses do
    member do
      get 'all_students'
    end
  end

  resources :waitlists do
    member do
      get 'remove_list'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_secure_password
  has_many :students
  has_many :courses, dependent: :destroy
  validates :email, :instructor_id, presence: true, uniqueness: true
  belongs_to :user, dependent: :destroy
  validates :name, :password_digest, :department, presence: true

  validates :email, format: {
    with: /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\z/i,
    message: "is Invalid",
    multiline: true
  }
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :correct_code, only: [:edit, :update, :destroy, :show]
  before_action :set_instructor, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]

  # GET /instructors or /instructors.json
  def index
    unless check_permissions?(session[:user_role], "view_instructor")
      redirect_to root_path
    end
    @instructors = Instructor.all.order("instructor_id ASC")
  end

  # GET /instructors/1 or /instructors/1.json
  def show
    unless check_permissions?(session[:user_role], "show_instructor")
      redirect_to root_path
    end
  end

  # GET /instructors/new
  def new
    if !current_user.nil? and check_permissions?(session[:user_role], "create_instructor")
      redirect_to root_path
    end
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
    unless check_permissions?(session[:user_role], "edit_instructor")
      redirect_to root_path
    end
  end

  def correct_user
    if current_user.user_role != 'admin'
      @instructor = Instructor.find_by_id(params[:id])
      if !current_user.nil? && @instructor.user_id != current_user.id
        redirect_to root_path
      end
    end
  end

  def correct_code
    if Instructor.find_by_id(params[:id]).nil?
      redirect_to root_path
    end
  end

  # POST /instructors or /instructors.json
  def create
    if !current_user.nil? && !check_permissions?(session[:user_role], "create_instructor")
      redirect_to root_path
    end
    email = params[:instructor][:email]
    user = { :email => email, :user_role => 'instructor' }
    @instructor = nil
    @user = User.new(user)

    respond_to do |format|
      if @user.save
        @instructor = Instructor.new(instructor_params)
        @instructor.user_id = @user.id
        if @instructor.save
          if not current_user.nil? and current_user.user_role == "admin"
            format.html { redirect_to @instructor, notice: "Instructor was successfully created by Admin." }
            format.json { render :show, status: :created, location: @instructor }
          else
            format.html { redirect_to login_path, notice: "Instructor was successfully created." }
            format.json { render :show, status: :created, location: @instructor }
          end
        else
          User.where(id: @user.id)[0].destroy
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @instructor.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /instructors/1 or /instructors/1.json
  def update
    unless check_permissions?(session[:user_role], "update_instructor")
      redirect_to root_path
    end
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to instructor_url(@instructor), notice: "Instructor was successfully updated." }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_instructor_students
    unless check_permissions?(session[:user_role], "show_instructor_students")
      redirect_to root_path
    end
    @enrollments = Enrollment.where(instructor_id: Instructor.find_by_user_id(session[:user_id]).id).order("student_code ASC")
    @waitlists = Waitlist.where(instructor_id: Instructor.find_by_user_id(session[:user_id]).id).order("student_code ASC")
  end

  # DELETE /instructors/1 or /instructors/1.json
  def destroy
    unless check_permissions?(session[:user_role], "delete_instructor")
      redirect_to root_path
    end
    @instructor.destroy

    respond_to do |format|
      format.html { redirect_to instructors_url, notice: "Instructor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_instructor
    @instructor = Instructor.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def instructor_params
    params.require(:instructor).permit(:instructor_id, :name, :email, :password, :department)
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_with(model: instructor) do |form| %>
  <% if instructor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
        <% instructor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label "Instructor ID", style: "display: block" %>
    <%= form.text_field :instructor_id %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :department, style: "display: block" %>
    <%= form.text_field :department %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/instructors/_instructor.html.erb
<div id="<%= dom_id instructor %>">
  <p>
    <strong>Instructor:</strong>
    <%= instructor.instructor_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= instructor.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= instructor.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= instructor.password %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= instructor.department %>
  </p>

</div>

app/views/instructors/edit.html.erb
<h1>Editing instructor</h1>

<%= render "form", instructor: @instructor %>

<br>

<div>
  <%= link_to "Show this instructor", @instructor %> |
  <%= link_to "Back to instructors", instructors_path %>
</div>

app/views/instructors/index.html.erb
<h1>Instructors</h1>

<table>
  <thead>
  <tr>
    <th> Instructor ID</th>
    <th> Name</th>
    <th> Email</th>
    <th> Department</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @instructors.each do |instructor| %>
    <tr>
      <td><%= instructor.instructor_id %></td>
      <td><%= instructor.name %></td>
      <td><%= instructor.email %></td>
      <td><%= instructor.department %></td>
      <% if current_user.user_role == 'admin' %>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<% if current_user.user_role == 'admin' %>
  <%= link_to "New instructor", new_instructor_path %>
<% end %>

app/views/instructors/new.html.erb
<h1>New instructor</h1>

<%= render "form", instructor: @instructor %>

<br>

<div>
  <% if current_user %>
    <%= link_to "Back to instructors", instructors_path %>
  <% else %>

  <% end %>
</div>

app/views/instructors/show.html.erb
<p>
  <strong>Instructor ID:</strong>
  <%= @instructor.instructor_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @instructor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @instructor.email %>
</p>

<p>
  <strong>Department:</strong>
  <%= @instructor.department %>
</p>

<div>
  <%= link_to "Edit this instructor", edit_instructor_path(@instructor) %> <br><br>
  <%= button_to "Destroy this instructor", @instructor, method: :delete %><br>
  <%= link_to "Back to instructors", instructors_path %>
</div>

app/views/instructors/show_instructor_students.html.erb
<h1>My Students</h1>

<h1>Enrollments</h1>
<table>
  <thead>
  <tr>
    <th>Course Code</th>
    <th>Course Name</th>
    <th>Student Code</th>
    <th>Student Name</th>
    <th>Email</th>
    <th>Date of Birth</th>
    <th>Phone Number</th>
    <th>Major</th>
    <th>Status</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @enrollments.each do |enrollment| %>
    <tr>
      <td><%= enrollment.course_code %></td>
      <td><%= Course.find_by_course_code(enrollment.course_code).name %></td>
      <td><%= enrollment.student_code %></td>
      <td><%= Student.find_by_id(enrollment.student_id).name %></td>
      <td><%= Student.find_by_id(enrollment.student_id).email %></td>
      <td><%= Student.find_by_id(enrollment.student_id).date_of_birth %></td>
      <td><%= Student.find_by_id(enrollment.student_id).phone_number %></td>
      <td><%= Student.find_by_id(enrollment.student_id).major %></td>
      <td> Enrolled</td>
      <td><%= link_to 'Unenroll', unenroll_enrollment_path(enrollment), method: :post, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br><br>

<h1>Waitlists</h1>

<table>
  <thead>
  <tr>
    <th>Course Code</th>
    <th>Course Name</th>
    <th>Student Code</th>
    <th>Student Name</th>
    <th>Email</th>
    <th>Date of Birth</th>
    <th>Phone Number</th>
    <th>Major</th>
    <th>Status</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @waitlists.each do |waitlist| %>
    <tr>
      <td><%= waitlist.course_code %></td>
      <td><%= Course.find_by_course_code(waitlist.course_code).name %></td>
      <td><%= waitlist.student_code %></td>
      <td><%= Student.find_by_id(waitlist.student_id).name %></td>
      <td><%= Student.find_by_id(waitlist.student_id).email %></td>
      <td><%= Student.find_by_id(waitlist.student_id).date_of_birth %></td>
      <td><%= Student.find_by_id(waitlist.student_id).phone_number %></td>
      <td><%= Student.find_by_id(waitlist.student_id).major %></td>
      <td> Waitlisted</td>
      <td><%= link_to 'Remove', remove_list_waitlist_path(waitlist), method: :post, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%# if current_user.user_role != 'student' %>
<%= link_to "New Enrollment", new_enrollment_path %><br><br>
<%#= link_to "New Waitlist", new_waitlist_path %>
<%# end %>
<%#= link_to 'Back', root_path %>