config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  resources :admins
  resources :instructors
  resources :waitlists
  resources :students
  resources :courses
  resources :enrollments
  resources :sessions, only: [:new, :create, :destroy]
  get 'admin_signup', to: "admins#new", as: 'admin_signup'
  get 'student_signup', to: "students#new", as: 'student_signup'
  get 'instructor_signup', to: "instructors#new", as: 'instructor_signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get 'instructor_courses', to: "courses#show_instructor_courses", as: "instructor_courses"
  get 'student_enrollments', to: "courses#show_student_enrolled_courses", as: "student_enrollments"
  get 'show_instructor_students_enrolled', to: "enrollments#show_instructor_students_enrolled", as: "show_instructor_students_enrolled"
  get 'show_instructor_students_waitlisted', to: "waitlists#show_instructor_students_waitlisted", as: "show_instructor_students_waitlisted"
  get 'student_waitlists', to: "courses#show_student_waitlisted_courses", as: "student_waitlists"
  get 'all_enrollments', to: "admins#all_enrollments", as: "all_enrollments"
  get 'show_instructor_students' , to: "instructors#show_instructor_students", as: "show_instructor_students"
  resources :courses do
    member do
      get 'enroll'
    end
  end
  resources :enrollments do
    member do
      get 'unenroll'
    end
  end
  resources :courses do
    member do
      get 'drop'
    end
  end

  resources :courses do
    member do
      get 'drop_waitlist'
    end
  end

  resources :courses do
    member do
      get 'all_students'
    end
  end

  resources :waitlists do
    member do
      get 'remove_list'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorized, only: [:index]

  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<% if current_user %>
  <br><br><%= link_to "Logout", logout_path %>
<% end %>

app/views/home/_header.html.erb
<%= link_to 'Home page', root_path %>
<h1>MyPack Lite</h1>

<p style="color: green"><%= notice %></p>
<b><p style="color: red"><%= alert %></p></b>

<% if current_user %>
  <% if current_user.user_role == "student" %>
    Name: <%= Student.find_by_email(current_user.email).name.to_s.gsub(/\b('?[a-z])/) { $1.capitalize } %>
    <br><br>
    Role: <strong><%= current_user.user_role.to_s.gsub(/\b('?[a-z])/) { $1.capitalize } %></strong>
  <% elsif current_user.user_role == "instructor" %>
    Name: <%= Instructor.find_by_email(current_user.email).name.to_s.gsub(/\b('?[a-z])/) { $1.capitalize } %>
    <br><br>
    Role: <strong><i><%= current_user.user_role.to_s.gsub(/\b('?[a-z])/) { $1.capitalize } %></i></strong>
  <% elsif current_user.user_role == "admin" %>
    Name: Admin
    <br><br>
    Role: <u><%= current_user.user_role.to_s.gsub(/\b('?[a-z])/) { $1.capitalize } %></u>
  <% end %>
<% end %>

app/views/home/index.html.erb
<!--<p id=”notice”><%#= notice %></p>-->

<p>Welcome to the Student Enrollment system</p>
<p>Enroll In courses at the snap of your finger </p>

<% if current_user %>
  </br>

  <% if current_user.user_role == "student" %>
    <%= link_to "All Courses", courses_path %> <br><br>
    <%= link_to "My Enrollments", student_enrollments_path %> <br><br>
    <%= link_to "My Waitlists", student_waitlists_path %>

  <% elsif current_user.user_role == "instructor" %>
    <%= link_to "All Courses", courses_path %> <br><br>
    <%= link_to "My Courses", instructor_courses_path %> <br><br>
    <!--    <%#= link_to "My Students", show_instructor_students_enrolled_path %><br><br>-->
    <!--    <%#= link_to "My Waitlist Students", show_instructor_students_waitlisted_path %><br><br>-->
    <%= link_to "My Students", show_instructor_students_path %>

  <% elsif current_user.user_role == "admin" %>
    <%= link_to "Show Profile", admins_path %> <br><br>
    <%= link_to "All Instructors", instructors_path %> <br><br>
    <%= link_to "All Students", students_path %> <br><br>
    <%= link_to "All Courses", courses_path %> <br><br>
    <%= link_to "All Enrollments", all_enrollments_path %>

  <% end %>
<% else %>
  <%= link_to "Login", login_path %><br><br>
  <%= link_to "Student Signup", student_signup_path %> <br><br>
  <%= link_to "Instructor Signup", instructor_signup_path %>

<% end %>