config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :users
  resources :admins
  resources :instructors
  resources :waitlists
  resources :students
  resources :courses
  resources :enrollments
  resources :sessions, only: [:new, :create, :destroy]
  get 'admin_signup', to: "admins#new", as: 'admin_signup'
  get 'student_signup', to: "students#new", as: 'student_signup'
  get 'instructor_signup', to: "instructors#new", as: 'instructor_signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get 'instructor_courses', to: "courses#show_instructor_courses", as: "instructor_courses"
  get 'student_enrollments', to: "courses#show_student_enrolled_courses", as: "student_enrollments"
  get 'show_instructor_students_enrolled', to: "enrollments#show_instructor_students_enrolled", as: "show_instructor_students_enrolled"
  get 'show_instructor_students_waitlisted', to: "waitlists#show_instructor_students_waitlisted", as: "show_instructor_students_waitlisted"
  get 'student_waitlists', to: "courses#show_student_waitlisted_courses", as: "student_waitlists"
  get 'all_enrollments', to: "admins#all_enrollments", as: "all_enrollments"
  get 'show_instructor_students' , to: "instructors#show_instructor_students", as: "show_instructor_students"
  resources :courses do
    member do
      get 'enroll'
    end
  end
  resources :enrollments do
    member do
      get 'unenroll'
    end
  end
  resources :courses do
    member do
      get 'drop'
    end
  end

  resources :courses do
    member do
      get 'drop_waitlist'
    end
  end

  resources :courses do
    member do
      get 'all_students'
    end
  end

  resources :waitlists do
    member do
      get 'remove_list'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :correct_code, only: [:edit, :update, :destroy, :show]
  before_action :set_enrollment, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy, :show]


  # GET /enrollments or /enrollments.json
  def index
    unless check_permissions?(session[:user_role], "view_enrollment")
      redirect_to root_path
    end
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
    unless check_permissions?(session[:user_role], "show_enrollment")
      redirect_to root_path
    end
  end

  # GET /enrollments/new
  def new
    unless check_permissions?(session[:user_role], "create_enrollment")
      redirect_to root_path
    end
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
    unless check_permissions?(session[:user_role], "edit_enrollment")
      redirect_to root_path
    end
  end

  def correct_user
    @enrollment = Enrollment.find_by_id(params[:id])
    if current_user.user_role == 'instructor'
      if !current_user.nil? && Instructor.find_by_id(@enrollment.instructor_id).user_id != current_user.id
        redirect_to root_path
      end
    end
    if current_user.user_role == 'student'
      if !current_user.nil? && Student.find_by_id(@enrollment.student_id).user_id != current_user.id
        redirect_to root_path
      end
    end
  end

  def correct_code
    if Enrollment.find_by_id(params[:id]).nil?
      redirect_to root_path
    end
  end

  def show_instructor_students_enrolled
    unless check_permissions?(session[:user_role], "show_instructor_students_enrolled")
      redirect_to root_path
    end
    @enrollments = Enrollment.where(instructor_id: Instructor.find_by_user_id(session[:user_id]).id)
  end

  # POST /enrollments or /enrollments.json
  def create
    unless check_permissions?(session[:user_role], "create_enrollment")
      redirect_to root_path
    end

    @enrollment = Enrollment.new(enrollment_params)
    @course = Course.find_by_course_code(@enrollment.course_code)
    @student = Student.find_by_student_id(@enrollment.student_code)

    if @student.nil?
      flash[:alert] = "Student doesn't exist"
      redirect_to new_enrollment_path
      return
    elsif @course.nil?
      flash[:alert] = "Course doesn't exist"
      redirect_to new_enrollment_path
      return
    end

    @instructor = Instructor.find_by_id(@course.instructor_id)

    if @course.status == 'WAITLIST'
      @waitlist = Waitlist.new
      @waitlist.student_code = @enrollment.student_code
      @waitlist.course_code = @course.course_code
      @waitlist.student_id = @student.id
      @waitlist.course_id = @course.id
      @waitlist.instructor_id = @instructor.id
    end

    @enrollment.student_id = @student.id
    @enrollment.course_id = @course.id
    @enrollment.instructor_id = @instructor.id

    already_enrolled = !Enrollment.where(student_id: @student.id, course_id: @course.id)[0].nil?
    already_waitlisted = !Waitlist.where(student_id: @student.id, course_id: @course.id)[0].nil?
    respond_to do |format|
      if current_user.user_role == 'instructor'
        if session[:user_id] == @instructor.user_id
          if already_enrolled
            format.html { redirect_to show_instructor_students_path, alert: @student.name.to_s + " is already enrolled in " + @course.course_code.to_s }
            format.json { render json: @enrollment.errors, status: :unprocessable_entity }
          else
            if @course.status == 'WAITLIST'
              if already_waitlisted
                format.html { redirect_to show_instructor_students_path, alert: @student.name.to_s + " is already waitlisted in " + @course.course_code.to_s }
                format.json { render json: @waitlist.errors, status: :unprocessable_entity }
              else
                if @course.students_waitlisted < @course.waitlist_capacity
                  if @waitlist.save
                    format.html { redirect_to show_instructor_students_path, notice: @student.name.to_s + " is successfully waitlisted in " + @course.course_code.to_s }
                    format.json { render :show, status: :created, location: @enrollment }
                    @course.update(students_waitlisted: (@course.students_waitlisted + 1))
                    if @course.waitlist_capacity == @course.students_waitlisted
                      @course.update(status: "CLOSED")
                    end
                  else
                    format.html { render :new, status: :unprocessable_entity }
                    format.json { render json: @waitlist.errors, status: :unprocessable_entity }
                  end
                else
                  format.html { redirect_to show_instructor_students_path, alert: "Waitlist capacity is full" }
                  format.json { render json: @waitlist.errors, status: :unprocessable_entity }
                end
              end
            elsif @course.status == 'CLOSED'
              format.html { redirect_to show_instructor_students_path, alert: @student.name.to_s + " can't be enrolled in " + @course.course_code.to_s + " since, the course is CLOSED" }
              format.json { render json: @enrollment.errors, status: :unprocessable_entity }
            else
              if @enrollment.save
                format.html { redirect_to show_instructor_students_path, notice: @student.name.to_s + " is successfully enrolled in " + @course.course_code.to_s }
                format.json { render :show, status: :created, location: @enrollment }
                @course.update(students_enrolled: (@course.students_enrolled + 1))
                if @course.capacity == @course.students_enrolled
                  if @course.students_waitlisted < @course.waitlist_capacity
                    @course.update(status: "WAITLIST")
                  else
                    @course.update(status: "CLOSED")
                  end
                end
              else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @enrollment.errors, status: :unprocessable_entity }
              end
            end
          end
        else
          format.html { redirect_to show_instructor_students_path, alert: "You cannot enroll student in courses other than yours" }
          format.json { render json: @enrollment.errors, status: :unprocessable_entity }
        end
      elsif current_user.user_role == "admin"
        if already_enrolled
          format.html { redirect_to enrollments_path, alert: @student.name.to_s + " is already enrolled in " + @course.course_code.to_s }
          format.json { render json: @enrollment.errors, status: :unprocessable_entity }
        else
          if @course.status == 'WAITLIST'
            if already_waitlisted
              format.html { redirect_to enrollments_path, alert: @student.name.to_s + " is already waitlisted in " + @course.course_code.to_s }
              format.json { render json: @waitlist.errors, status: :unprocessable_entity }
            else
              if @course.students_waitlisted < @course.waitlist_capacity
                if @waitlist.save
                  format.html { redirect_to waitlists_path, notice: @student.name.to_s + " is successfully waitlisted in " + @course.course_code.to_s }
                  format.json { render :show, status: :created, location: @enrollment }
                  @course.update(students_waitlisted: (@course.students_waitlisted + 1))
                  if @course.waitlist_capacity == @course.students_waitlisted
                    @course.update(status: "CLOSED")
                  end
                else
                  format.html { render :new, status: :unprocessable_entity }
                  format.json { render json: @waitlist.errors, status: :unprocessable_entity }
                end
              else
                format.html { redirect_to admins, alert: "Waitlist capacity is full" }
                format.json { render json: @waitlist.errors, status: :unprocessable_entity }
              end
            end
          elsif @course.status == 'CLOSED'
            format.html { redirect_to enrollments_path, alert: @student.name.to_s + " can't be enrolled in " + @course.course_code.to_s + " since, the course is CLOSED" }
            format.json { render json: @enrollment.errors, status: :unprocessable_entity }
          else
            if @enrollment.save
              format.html { redirect_to enrollments_path, notice: @student.name.to_s + " is successfully enrolled in " + @course.course_code.to_s }
              format.json { render :show, status: :created, location: @enrollment }
              @course.update(students_enrolled: (@course.students_enrolled + 1))
              if @course.capacity == @course.students_enrolled
                if @course.students_waitlisted < @course.waitlist_capacity
                  @course.update(status: "WAITLIST")
                else
                  @course.update(status: "CLOSED")
                end
              end
            else
              format.html { render :new, status: :unprocessable_entity }
              format.json { render json: @enrollment.errors, status: :unprocessable_entity }
            end
          end
        end
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    unless check_permissions?(session[:user_role], "update_enrollment")
      redirect_to root_path
    end

    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div id="<%= dom_id enrollment %>">
  <p>
    <strong>Student:</strong>
    <%= enrollment.student_code %>
  </p>

  <p>
    <strong>Course:</strong>
    <%= enrollment.course_code %>
  </p>

</div>

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Student ID", style: "display: block" %>
    <%= form.select :student_code, Student.all.order("student_id ASC").collect { |x| [x.student_id] } %>
    <%#= form.text_field :student_code %>
  </div>

  <div>
    <%= form.label "Course Code", style: "display: block" %>
    <%= form.select :course_code, Course.all.order("course_code ASC").collect { |x| [x.course_code] } %>
    <%#= form.text_field :course_code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Show this enrollment", @enrollment %> |
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/index.html.erb
<h1>Enrollments</h1>

<table>
  <thead>
  <tr>
    <th> Student ID</th>
    <th> Course Code</th>
    <th colspan="1"></th>
  </tr>
  </thead>
  <tbody>
  <% @enrollments.each do |enrollment| %>
    <tr>
      <td><%= enrollment.student_code %></td>
      <td><%= enrollment.course_code %></td>
      <td> <%= link_to "Show this enrollment", enrollment %></td>
  <% end %>
  </tr>
  </tbody>
</table>

<br>
<% if current_user.user_role == 'admin' %>
  <%= link_to "All Enrollments", all_enrollments_path %>
<% end %>
<br><br>
<%= link_to "New enrollment", new_enrollment_path %>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>
<b><p style="color: red"><%= alert %></p></b>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show.html.erb
<%= render @enrollment %>

<div>
<!--  <%#= link_to "Edit this enrollment", edit_enrollment_path(@enrollment) %> <br><br>-->
  <%= button_to "Destroy this enrollment", @enrollment, method: :delete %><br>

  <% if current_user.user_role == 'admin' %>
    <%= link_to "All Enrollments", all_enrollments_path %> <br><br>
    <%elsif current_user.user_role == 'instructor' %>
    <%= link_to "My Students", show_instructor_students_path %><br><br>
  <% end %>

  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show_instructor_students_enrolled.html.erb
<h1>My Course Students</h1>

<table>
  <thead>
  <tr>
    <th>Course Code</th>
    <th>Student Code</th>
    <th>Student Name</th>
    <th>Email</th>
    <th>Date of Birth</th>
    <th>Phone Number</th>
    <th>Major</th>
    <th colspan="1"></th>
  </tr>
  </thead>

  <tbody>
  <% @enrollments.each do |enrollment| %>
    <tr>
      <td><%= enrollment.course_code %></td>
      <td><%= enrollment.student_code %></td>
      <td><%= Student.find_by_id(enrollment.student_id).name %></td>
      <td><%= Student.find_by_id(enrollment.student_id).email %></td>
      <td><%= Student.find_by_id(enrollment.student_id).date_of_birth %></td>
      <td><%= Student.find_by_id(enrollment.student_id).phone_number %></td>
      <td><%= Student.find_by_id(enrollment.student_id).major %></td>
      <td><%= link_to 'Unenroll', unenroll_enrollment_path(enrollment), method: :post, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>



<%# if current_user.user_role != 'student' %>
<%= link_to "New Enrollment", new_enrollment_path %><br><br>
<%= link_to "New Waitlist", new_waitlist_path %>
<%# end %>
<%#= link_to 'Back', root_path %>